Updated IngestService to use new UniversalMetricFrame
racker/salus-event-engine-ingest pull request #30
Opened 2020-09-18 11:01 UTC by rohitsngh27

# Resolves
https://jira.rax.io/browse/SALUS-1004?

# What
Update IngestService to use UniversalMetricFrame schema

# How
Changes is IngestService class to use new UniversalMetricFrameSchema

# How to test
This can be tested via unit test cases

2020-09-18 11:02 UTC, rohitsngh27 commented on src/main/java/com/rackspace/salus/event/ingest/services/IngestService.java
> +    metric.getMetricsList().stream().forEach(val -> {
Not sure about this logic here.

2020-09-18 14:54 UTC, itzg requested changes

2020-09-18 14:54 UTC, itzg commented on src/main/java/com/rackspace/salus/event/ingest/services/IngestService.java
> +    Timestamp protobufTimestamp = metric.getMetrics(0).getTimestamp();
A similar TODO comment would be good here

2020-09-18 14:54 UTC, itzg commented on src/main/java/com/rackspace/salus/event/ingest/services/IngestService.java
> +    metric.getMetricsList().stream().forEach(val -> {
Protobuf generates a `get{field}Case` method to determine which of the `oneof` fields is set:

https://developers.google.com/protocol-buffers/docs/reference/java-generated#oneof

For this one, the method is `getValueCase()`

2020-09-18 20:35 UTC, itzg requested changes

2020-09-18 20:35 UTC, itzg commented on src/main/java/com/rackspace/salus/event/ingest/services/IngestService.java
> +    // TODO adjust recipient selection to handle non-Salus metrics
```suggestion
    // TODO adjust timestamp, measurement, and tags to handle non-Salus metrics
```

2020-09-18 20:35 UTC, itzg commented on src/main/java/com/rackspace/salus/event/ingest/services/IngestService.java
> +      switch (valueCase) {
`val.getValueCase()` seems to return a `Metric.ValueCase` so just this should work:
```suggestion
      switch (val.getValueCase()) {
```

2020-09-18 20:35 UTC, itzg commented on src/main/java/com/rackspace/salus/event/ingest/services/IngestService.java
> +          pointBuilder.addField(val.getName(), val.getString());
To be safe, like if a new case is added later:
```suggestion
        case STRING:
          pointBuilder.addField(val.getName(), val.getString());
          break;
```

2020-09-21 13:29 UTC, itzg approved these changes

2020-09-21 13:54 UTC, merged